name: "CI"
on:
#  push:
#    branches:
#      - '*'
#      - '!master'
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Check out the code"
        uses: actions/checkout@master

      - name: "Set up Java"
        uses: actions/setup-java@master
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: "Build and test"
        run: ./gradlew --no-daemon build

      - name: "Test Report"
        uses: dorny/test-reporter@v2
        if: success() || failure()
        with:
          name: "Gradle Tests"
          path: build/test-results/test/*.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: 'true'
          use-actions-summary: 'true'